# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f272f762c4f2d49795dbd3defb2b343c6acbb86e056bb0bbe0f88e8645adba543d72739466315090680ad3d7d389e9f7c5e4aba24ae1040557e2cc6581dc3174

test:
  secret_key_base: cf5e46354bf63d3a3c954be5324963c74adac1c96361381decc1fac52b616d3bd8f6922db440eaffe484539a5e038f75b8a36e9133b7acc79c024e5236cf6030

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
